---
# chromium Packages

- name: install lists packages
  apt: pkg={{ item }} state=installed
  become: yes
  become_user: root

  with_items:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg
    - chromium-codecs-ffmpeg-extra

