##
# Ansible playbook 
#

- hosts: local
  become: yes
  become_user: alex

  roles:
    - vmbox
  # - base
  # - python
  # - utils
  # - virtualenv
  # - chromium
  # - docker
  # - pycharm
  # - conky
  # - desktop
