##
# Ansible playbook 
#

- hosts: local
  become: yes
  become_user: alex

  roles:
    # Rolls installed with apt
     - base
     - utils
     - chromium
     - python
     - vmbox
     - vagrant
     - virtualenv
    # - conky
    # - desktop
    # - latex
    # - openssh

    # Rolls used with curl

    # - docker
    # - pycharm
    # - packer
    # - rancher
    # - terraform


