##
# Ansible playbook 
#

- hosts: all
  become: yes
  become_user: alex

  roles:
    # Rolls installed with apt
    - base
    - utils
    - chromium
    - python
    - vmbox
    - vagrant
    - conky
    - latex
    - wireshark

    # Rolls used with curl
    - docker
    - pycharm


    ## TODO check
    #-webstrom
    #-idea
    #- openssh
    # - packer
    # - rancher
    # - terraform
    #- virtualenv
    #- desktop


