---

# Install Python packages

- name: install lists packages
  apt: pkg={{ item }} state=installed
  become: yes
  become_user: root

  with_items:
    - python-pip
    - python3-pip
    - bpython3

#- name: Configure | add to PATH
 # copy: src=set-alias.sh
  #      dest=/etc/profile.d
  #sudo: yes






